export const TOGGLE_SEARCH = "TOGGLE_SEARCH";
export const TOGGLE_FORM = "TOGGLE_FORM";
export const TOGGLE_MENU = "TOGGLE_MENU";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE"; 
export const RESET_NAVIGATION = "RESET_NAVIGATION";